import type {EditorProject, ProjectMedia} from "./types";
import {DEFAULT_EFFECTS, DEFAULT_TITLE_STYLE, DEFAULT_TRANSFORM} from "./types";

export const sampleProject: EditorProject = {
  activeSequenceId: "sequence-1",
  sequences: [],
  name: "Game Library Launch",
  width: 1920,
  height: 1080,
  fps: 30,
  durationInFrames: 450,
  markers: [
    {id: "marker-intro", frame: 105, label: "Montage starts", color: "#f6c85f"},
    {id: "marker-impact", frame: 300, label: "Final beat", color: "#ff718d"},
  ],
  transitions: [],
  mediaBins: [
    {id: "bin-video", name: "Video"},
    {id: "bin-audio", name: "Audio"},
    {id: "bin-graphics", name: "Graphics"},
  ],
  media: [],
  tracks: [
    {id: "c1", name: "C1", kind: "caption", muted: false, solo: false, volume: 1, hidden: false, locked: false},
    {id: "v3", name: "V3", kind: "video", muted: false, solo: false, volume: 1, hidden: false, locked: false},
    {id: "v2", name: "V2", kind: "video", muted: false, solo: false, volume: 1, hidden: false, locked: false},
    {id: "v1", name: "V1", kind: "video", muted: false, solo: false, volume: 1, hidden: false, locked: false},
    {id: "a1", name: "A1", kind: "audio", muted: false, solo: false, volume: 1, hidden: false, locked: false},
    {id: "a2", name: "A2", kind: "audio", muted: false, solo: false, volume: 1, hidden: false, locked: false},
  ],
  clips: [
    {
      id: "title-1",
      name: "Opening title",
      kind: "title",
      trackId: "v3",
      start: 10,
      duration: 72,
      sourceStart: 0,
      color: "#9b7cff",
      volume: 1,
      fadeIn: 0,
      fadeOut: 0,
      audioMuted: false,
      transform: {...DEFAULT_TRANSFORM, y: 180},
      effects: {...DEFAULT_EFFECTS},
      keyframes: [],
      text: "PLAY THE FUTURE",
      textStyle: {...DEFAULT_TITLE_STYLE},
    },
    {
      id: "video-1",
      name: "Library hero",
      kind: "video",
      trackId: "v1",
      start: 0,
      duration: 105,
      sourceStart: 0,
      src: "/trailers/game-library-launch/game-library.mov",
      color: "#4e8cff",
      volume: 0.8,
      fadeIn: 0,
      fadeOut: 0,
      audioMuted: false,
      transform: {...DEFAULT_TRANSFORM},
      effects: {...DEFAULT_EFFECTS, contrast: 108},
      keyframes: [],
      sourceMediaId: "m1",
    },
    {
      id: "video-2",
      name: "Golf Galaxy",
      kind: "video",
      trackId: "v1",
      start: 105,
      duration: 90,
      sourceStart: 20,
      src: "/trailers/game-library-launch/golf-galaxy.mov",
      color: "#35b9a6",
      volume: 0.8,
      fadeIn: 0,
      fadeOut: 0,
      audioMuted: false,
      transform: {...DEFAULT_TRANSFORM},
      effects: {...DEFAULT_EFFECTS, saturation: 112},
      keyframes: [],
      sourceMediaId: "m2",
    },
    {
      id: "video-3",
      name: "infiNFT Rush",
      kind: "video",
      trackId: "v1",
      start: 195,
      duration: 105,
      sourceStart: 0,
      src: "/trailers/game-library-launch/infinft-rush.mov",
      color: "#ee7d49",
      volume: 0.8,
      fadeIn: 0,
      fadeOut: 0,
      audioMuted: false,
      transform: {...DEFAULT_TRANSFORM},
      effects: {...DEFAULT_EFFECTS},
      keyframes: [],
      sourceMediaId: "m3",
    },
    {
      id: "video-4",
      name: "Monster Mayhem",
      kind: "video",
      trackId: "v1",
      start: 300,
      duration: 120,
      sourceStart: 15,
      src: "/trailers/game-library-launch/monster-mayhem.mov",
      color: "#d95688",
      volume: 0.8,
      fadeIn: 0,
      fadeOut: 0,
      audioMuted: false,
      transform: {...DEFAULT_TRANSFORM},
      effects: {...DEFAULT_EFFECTS, brightness: 105},
      keyframes: [],
      sourceMediaId: "m4",
    },
    {
      id: "image-1",
      name: "Royale card",
      kind: "image",
      trackId: "v2",
      start: 120,
      duration: 54,
      sourceStart: 0,
      src: "/trailers/game-library-launch/infinft-royale.png",
      color: "#b46cff",
      volume: 1,
      fadeIn: 0,
      fadeOut: 0,
      audioMuted: false,
      transform: {...DEFAULT_TRANSFORM, x: 520, y: -220, scale: 32, rotation: 4},
      effects: {...DEFAULT_EFFECTS},
      keyframes: [],
      sourceMediaId: "m8",
    },
    {
      id: "audio-1",
      name: "Score bed",
      kind: "audio",
      trackId: "a1",
      start: 0,
      duration: 420,
      sourceStart: 0,
      src: "/audio/synth/score-bed.wav",
      color: "#3abb78",
      volume: 0.55,
      fadeIn: 18,
      fadeOut: 24,
      audioMuted: false,
      transform: {...DEFAULT_TRANSFORM},
      effects: {...DEFAULT_EFFECTS},
      keyframes: [],
      sourceMediaId: "m6",
    },
    {
      id: "audio-2",
      name: "Impact",
      kind: "audio",
      trackId: "a2",
      start: 102,
      duration: 38,
      sourceStart: 0,
      src: "/audio/synth/boom-big.wav",
      color: "#68a94f",
      volume: 0.9,
      fadeIn: 3,
      fadeOut: 8,
      audioMuted: false,
      transform: {...DEFAULT_TRANSFORM},
      effects: {...DEFAULT_EFFECTS},
      keyframes: [],
      sourceMediaId: "m7",
    },
  ],
};

export const mediaItems: ProjectMedia[] = [
  {id: "m1", name: "Game library", kind: "video", src: "/trailers/game-library-launch/game-library.mov", duration: 105, color: "#4e8cff", binId: "bin-video", fileName: "game-library.mov", mimeType: "video/quicktime", width: 1920, height: 1080, renderReady: true},
  {id: "m2", name: "Golf Galaxy", kind: "video", src: "/trailers/game-library-launch/golf-galaxy.mov", duration: 120, color: "#35b9a6", binId: "bin-video", fileName: "golf-galaxy.mov", mimeType: "video/quicktime", width: 1920, height: 1080, renderReady: true},
  {id: "m3", name: "infiNFT Rush", kind: "video", src: "/trailers/game-library-launch/infinft-rush.mov", duration: 120, color: "#ee7d49", binId: "bin-video", fileName: "infinft-rush.mov", mimeType: "video/quicktime", width: 1920, height: 1080, renderReady: true},
  {id: "m4", name: "Monster Mayhem", kind: "video", src: "/trailers/game-library-launch/monster-mayhem.mov", duration: 135, color: "#d95688", binId: "bin-video", fileName: "monster-mayhem.mov", mimeType: "video/quicktime", width: 1920, height: 1080, renderReady: true},
  {id: "m5", name: "Abandoned", kind: "video", src: "/trailers/game-library-launch/abandoned.mov", duration: 120, color: "#aa724f", binId: "bin-video", fileName: "abandoned.mov", mimeType: "video/quicktime", width: 1920, height: 1080, renderReady: true},
  {id: "m6", name: "Score bed", kind: "audio", src: "/audio/synth/score-bed.wav", duration: 420, color: "#3abb78", binId: "bin-audio", fileName: "score-bed.wav", mimeType: "audio/wav", renderReady: true},
  {id: "m7", name: "Impact", kind: "audio", src: "/audio/synth/boom-big.wav", duration: 38, color: "#68a94f", binId: "bin-audio", fileName: "boom-big.wav", mimeType: "audio/wav", renderReady: true},
  {id: "m8", name: "Royale card", kind: "image", src: "/trailers/game-library-launch/infinft-royale.png", duration: 150, color: "#b46cff", binId: "bin-graphics", fileName: "infinft-royale.png", mimeType: "image/png", width: 1920, height: 1080, renderReady: true},
];

sampleProject.media = mediaItems.map((item) => ({...item}));
